### ISSUE TITLE
Is your parse_timestamp() function correct?

### ISSUE THREAD

**Issue by noah-kg** [ChrisCrossCrash/r-place-blender#3]
I'm trying to go through your project on my own machine, and I'm getting different values for the timestamps. Your method says to convert each pixel's timestamp into the number of milliseconds since the first pixel was placed. I'm following along and I get these as my first 10 timestamps in ms:

```
0          #<--- 1st pixel
2181
3108
65964
84730
89063
103321
108798
125591
135853 
```

I also noticed we have different START_TIME values, but honestly I'm unsure if that has to do with timezone differences. My START_TIME is 1649058831577, and yours is 1648806250315.

Additionally, when I run the following code, I get a completely different value from you:

```
# Parse a sample timestamp.
parse_timestamp("2022-04-04 00:55:40.375 UTC")
```

That timestamp corresponds to the 8th pixel placed, which is the difference between these two timestamps:
```
# just the time portion
00:55:40.375  #8th pixel
00:53:51.577  #1st pixel
```
Doing the math manually, that is a difference of 1 minute and 48.798 seconds, which converts to 108,798ms. However, you end up with 216,690,060. If this is supposed to be the number of milliseconds since the first pixel placement, that means the 8th pixel was placed over 60 hours later?

I apologize if I'm not understanding it correctly. Here is the code I made for my function:

```
def parse_time(ts):
    date_fmt  = '%Y-%m-%d %H:%M:%S.%f %Z'
    date_fmt2 = '%Y-%m-%d %H:%M:%S %Z' #exactly on the second

    try:
        #convert to POSIX timestamp
        ts = datetime.strptime(ts, date_fmt).timestamp()
    except ValueError:
        #timestamp is on the second (no decimal points) - happens 1/1000 of the time
        ts = datetime.strptime(ts, date_fmt2).timestamp()

    ts *= 1000.0
    ts = int(ts)
    ts -= START_TIME
    return ts
```

Obviously you got your program to run and you were able to move onto the Blender section with it, but I've been having some issues getting my timestamps in order.

**Comment by noah-kg** [comment]
Oh man... Of course I realized my mistake right after opening this issue. I was focused on the time portion of the timestamp so much I failed to see that the date was 04-04, when r/place started on 04-01. 

I'm sorry for wasting your time!

**Comment by ChrisCrossCrash** [comment]
@noah-kg Oh no worries! Good ol' [rubber duck debugging technique](https://en.wikipedia.org/wiki/Rubber_duck_debugging) to the rescue. I hope you are having fun with it. Let me know if you run into any more issues. I'd love to see the result!
