### ISSUE TITLE
animation fps in Blender 3.1

### ISSUE THREAD

**Issue by noah-kg** [ChrisCrossCrash/r-place-blender#4]
Hey again,

Did you have any issues with animation playback in Blender? I used to be pretty proficient in Blender 2.8, but I haven't touched in in over  a year... I've gotten my color and heat maps in Blender, but I can barely move the camera around or have any kind of playback. I have a fairly strong PC with an RTX 2070. Was there any special thing you did to make playback smoother?

**Comment by ChrisCrossCrash** [comment]
Unfortunately, I don't think you'll have much luck playing back the animation in real time. It needs to load both 2000x2000 color and heat maps on every frame, and then it needs to recalculate the mesh.

However, adjusting the Geometry Node min and max x and y values can really help make Blender more responsive.

![image](https://user-images.githubusercontent.com/40023417/165256694-228db902-50f7-43ea-b380-4870915f05c1.png)

Another tip: Try rendering in "Workbench", rather than Eevee or Cycles. I'm able to render a frame every 2 seconds or so on my old laptop. That way you can get a nice preview of the camera speed and pixel decay before you do a higher quality render.

Also, you've set up your [system settings](https://docs.blender.org/manual/en/latest/editors/preferences/system.html) and you are using the GPU compute option in the Cycles render settings, right?

**Comment by noah-kg** [comment]
Thanks! Yeah I'm starting to remember a lot of old Blender things now, haha. When you did your final renders, did you keep the samples to 1024? I generated 7200 frames last night with Python, and I'm trying to make a small animation on a particular section... I wanted 60fps, but then I realized I need to tell Blender to render from 0-3600 to keep it within 60 seconds... and *then* I realized that I only want to have a ~10 seconds or so long animation (similar to your Star Wars example), so now I'm in the process of just trying things out. If I get something good I'll let you know! :)

And yes, I'm using my GPU to render ;D

**Comment by ChrisCrossCrash** [comment]
> did you keep the samples to 1024?

I think that I used the settings that were saved in the `r-place.blend` file for all of my video renders so far. I'm working on a new very long video of the Canada flag right now, but I'm time limiting the renders to only 7 seconds with the OpenImageDenoise on the "Fast" setting. It only takes about 12 seconds per frame and the results are surprisingly good!

![image](https://user-images.githubusercontent.com/40023417/165402061-3cbbbbce-4a4c-495c-aedd-e9a7a2010653.png)
![0960](https://user-images.githubusercontent.com/40023417/165402185-5608eadf-a038-462f-8dfe-5f8a601ead43.png)

I'm looking forward to seeing your results!

**Comment by noah-kg** [comment]
https://user-images.githubusercontent.com/23434317/165411063-5f519fd7-a03c-4b01-947a-d5eec2d055d1.mp4

Here's a small version of my first attempt. Definitely needs some adjusting, but I'm still trying to figure out how to get it to look smooth and what not. I rendered most of the top half of the full canvas and the combined color and heat maps are like, 15GB, hah.

The clip I posted above was actually made with your age map version, as I kinda like how it looks a little more. I'm going to try with the heat maps again for a different, smaller area. I think my biggest difficulty is figuring out how many frames I should be importing into Blender, because that would obviously affect the playback length if you keep it at 60fps. I think your Star Wars clip is the perfect length, haha.

**Comment by ChrisCrossCrash** [comment]
Very nice! It's fun to see results from other people.

> The clip I posted above was actually made with your age map version, as I kinda like how it looks a little more.

Looks good! I think you could get a similar result with the newer version by decreasing the scale height to a low number, like 0.1 meters. Remember the scale height is how much the height increase drops off with increases initial height. So if the scale height was 0.1 meters, and the height increase from zero height was 0.1 meters, then a pixel which is already 0.1 meters tall would get a much smaller height increase after being changed.

```python
In [1]: from math import exp

In [2]: def calculate_pressure(P_0, z, H):
   ...:     """
   ...:     Given the initial pressure P_0, height z, and scale height H,
   ...:     calculate the pressure P(z) at the given height.
   ...:     """
   ...:     try:
   ...:         # Get the pressure when z is a single value.
   ...:         return P_0 * exp(-z / H)
   ...:     except TypeError:
   ...:         # This is a NumPy array.
   ...:         return P_0 * np.exp(-z / H)
   ...:

In [3]: # With zero initial height.

In [4]: calculate_pressure(0.1, 0, 0.1)
Out[4]: 0.1

In [5]: # With 0.1 meters initial pressure.

In [6]: calculate_pressure(0.1, 0.1, 0.1)
Out[6]: 0.036787944117144235
```

Just be careful of making the scale height _too_ small. If you make the scale height too small, then decaying pixels won't grow very much until their height gets back to around 0. So they will jump up really high, start decaying, and never make such a big jump as they did from zero. For example here, the initial height is only 0.02 meters and the scale height is 0.01 meters. A brand new pixel would see a height increase of 0.1 meters, but even a very short 0.02 meter tall pixel will only get a 0.0135 meter height increase.

```python
In [7]: # With 0.02 meters initial height, the height increase is tiny compared to a starting height of zero.

In [8]: calculate_pressure(0.1, 0.02, 0.01)
Out[8]: 0.013533528323661271
```

So I guess you can't really get the same effect with the new version, but you can get closer by adjusting the scale height. I was thinking of storing the age values in the red channel and the heat in the green channel, but I thought it would be better to keep it simpler so people can understand it easier.

> I think my biggest difficulty is figuring out how many frames I should be importing into Blender, because that would obviously affect the playback length if you keep it at 60fps.

Just think of it like this:

frames / <s>second</s> * <s>seconds</s> = frames

So if you want a 15 second video at 60 FPS:

60 frames/<s>second</s> * 15 <s>seconds</s> = 900 frames

You can also find out the timescale to use depending on how much time goes by in the simulation. For example if you know that it takes 1 hour for an artwork to be drawn, and you want to fit that 1 hour into a 15 second render, then:

1 hour = 1 <s>hour</s> * 60 <s>minutes</s>/<s>hour</s> * 60 seconds/<s>minute</s> = 3600 seconds

3600 <s>seconds</s> / 15 <s>seconds</s> = 240

So the playback will be at 240x speed. The timescale should be set to 240.

[Wolfram Alpha](https://www.wolframalpha.com) is really nice for figuring this stuff out without converting units:

![image](https://user-images.githubusercontent.com/40023417/165529582-db23e0a2-350d-4583-b34b-b10e1242f694.png)

**Comment by noah-kg** [comment]
That's very helpful information! I feel like you should include that information in the guide. :) Thank you very much once again! I've been learning quite a lot from this project. The data cleaning part was fairly straightforward, but I knew nothing about getting that data into Blender. I'll keep playing with this when I have some time in between studying/searching for jobs, haha.


On a side note: do you think there's a way to get the pixels to stop increasing after a certain time? For example, I was looking at an area that I liked, but there's no good... "clean" moment where the pixels aren't being updated, and it makes it a little difficult to see the whole artwork. I was thinking I could set some kind of flag or something that would tell the function to stop reading in new age/heat map information... and then get the current "tall" pixels to decay until all the visible pixels are flat.

**Comment by ChrisCrossCrash** [comment]
> I feel like you should include that information in the guide.

I will definitely take a look at making that a bit better documented. Thanks for pointing it out to me.

> On a side note: do you think there's a way to get the pixels to stop increasing after a certain time? For example, I was looking at an area that I liked, but there's no good... "clean" moment where the pixels aren't being updated, and it makes it a little difficult to see the whole artwork.

If you watch my [Star Wars](https://www.reddit.com/r/blender/comments/u0gtvs/a_long_time_ago_in_a_subreddit_far_far_away/?utm_source=share&utm_medium=web2x&context=3) and [Michigun Memorial](https://www.reddit.com/r/place/comments/u1745q/michigun_memorial_request/?utm_source=share&utm_medium=web2x&context=3) renders on Reddit you'll see that I animated the "Height Multiplier" setting in the geometry nodes down to zero in the last couple seconds. That way, they completely flatten out at the end, and you get an easy to see flat plane.

You could also change the `generate()` function so that it stops adding height after a certain frame, but then it would never get quite perfectly flat.

**Comment by noah-kg** [comment]
> I animated the "Height Multiplier" setting...

Damn, that's smart. I believe I now have all the information I need to more efficiently place with this. ^_^ 

Cheers!

**Comment by ChrisCrossCrash** [comment]
That's great! I checked out your other work on Reddit (at least I think it was you). Great stuff!

I'll close the issue for now, but feel free to open a new issue if you run into any more problems. Also let me know if you post anything using this project. Thanks for your interest!
